services:
  reg23-app-cpu:
    platform: linux/amd64
    image: eprager/reg23-app:cpu
    build:
      context: .
      dockerfile: docker/DockerfileCPU
    profiles: [ "cpu" ]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host

  reg23-app-cuda:
    image: eprager/reg23-app:cuda
    build:
      context: .
      dockerfile: docker/DockerfileCUDA
    profiles: [ "cuda" ]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]