name: "Build and deploy docs"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "[ reg23-experiments Python Docs ] Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"
          enable-cache: true

      - name: "[ reg23-experiments Python Docs ] Set up virtual environment"
        run: |
          uv venv .venv
          source .venv/bin/activate

      - name: "[ reg23-experiments Python Docs ] Create a fresh lock file from the pyproject.tomls"
        run: uv lock

      - name: "[ reg23-experiments Python Docs ] Install dependencies for the reg23-experiments package; this will in turn install the reg23-core package"
        working-directory: packages/reg23_experiments
        run: uv sync --extra cpu --group docs

      - name: "[ reg23-experiments Python Docs ] Build HTML with pdoc"
        run: uv run pdoc -o packages/reg23_experiments/docs packages/reg23_experiments/src/reg23_experiments \!reg23_experiments.io.external_datasets

      - name: "[ reg23 C++ Docs ] Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: "[ reg23 C++ Docs ] Build Doxygen HTML"
        working-directory: packages/reg23_core/Docs
        run: doxygen Doxyfile

      - name: "Stage combined docs for deployment"
        run: |
          mkdir -p site
          cp -r packages/reg23_core/Docs/build/html site/reg23
          cp -r packages/reg23_experiments/docs/. site/reg23_experiments

      - name: "Create landing page"
        run: |
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head><title>Documentation</title></head>
          <body>
            <h1>Documentation for reg23-experiments and reg23</h1>
            <p>Contributors: <a href="https://github.com/ewoprager">Edmund Prager<a/></p>
            <p><a href="https://github.com/ewoprager/grangeat-2d-3d-register-pytorch">GitHub repository</a></p>
            <ul>
              <li><a href="reg23/">reg23 C++ API Docs</a></li>
              <li><a href="reg23_experiments/">reg23-experiments Python API Docs</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: "Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
